package com.wangming.common.auto.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.util.Date;

public class AccountToken implements Serializable {
    /**
     * 
     * 表 : account_token
     * 对应字段 : id
     */
    private Integer id;

    /**
     * 微信公众号
     * 表 : account_token
     * 对应字段 : name
     */
    private String name;

    /**
     * 
     * 表 : account_token
     * 对应字段 : chinese_name
     */
    private String chineseName;

    /**
     * 公众号appid
     * 表 : account_token
     * 对应字段 : appid
     */
    private String appid;

    /**
     * 公众号appSecret
     * 表 : account_token
     * 对应字段 : secret
     */
    private String secret;

    /**
     * 
     * 表 : account_token
     * 对应字段 : access_token
     */
    private String accessToken;

    /**
     * 
     * 表 : account_token
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_token
     *
     * @MBG Generated Mon Apr 29 13:55:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return account_token.id：
     */
    public Integer getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get method 
     *
     * @return account_token.name：微信公众号
     */
    public String getName() {
        return name;
    }

    /**
     * set method 
     *
     * @param name  微信公众号
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get method 
     *
     * @return account_token.chinese_name：
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * set method 
     *
     * @param chineseName  
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName == null ? null : chineseName.trim();
    }

    /**
     * get method 
     *
     * @return account_token.appid：公众号appid
     */
    public String getAppid() {
        return appid;
    }

    /**
     * set method 
     *
     * @param appid  公众号appid
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * get method 
     *
     * @return account_token.secret：公众号appSecret
     */
    public String getSecret() {
        return secret;
    }

    /**
     * set method 
     *
     * @param secret  公众号appSecret
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * get method 
     *
     * @return account_token.access_token：
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * set method 
     *
     * @param accessToken  
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * get method 
     *
     * @return account_token.update_time：
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", chineseName=").append(chineseName);
        sb.append(", appid=").append(appid);
        sb.append(", secret=").append(secret);
        sb.append(", accessToken=").append(accessToken);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}