package com.wangming.common.auto.model;

import java.io.Serializable;
import java.util.Date;

public class BDMapDistance implements Serializable {
    /**
     * 
     * 表 : bdmap_distance
     * 对应字段 : id
     */
    private Integer id;

    /**
     * entity唯一标识
     * 表 : bdmap_distance
     * 对应字段 : entity_name
     */
    private String entityName;

    /**
     * service的ID
     * 表 : bdmap_distance
     * 对应字段 : service_id
     */
    private Integer serviceId;

    /**
     * 1为 gcj02：国测局加密坐标；2为 bd09ll：百度经纬度坐标
     * 表 : bdmap_distance
     * 对应字段 : coord_type_output
     */
    private String coordTypeOutput;

    /**
     * 开始时间
     * 表 : bdmap_distance
     * 对应字段 : start_time
     */
    private Date startTime;

    /**
     * 结束时间
     * 表 : bdmap_distance
     * 对应字段 : end_time
     */
    private Date endTime;

    /**
     * 轨迹里程
     * 表 : bdmap_distance
     * 对应字段 : distance
     */
    private Float distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bdmap_distance
     *
     * @MBG Generated Tue Feb 19 22:24:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return bdmap_distance.id：
     */
    public Integer getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get method 
     *
     * @return bdmap_distance.entity_name：entity唯一标识
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * set method 
     *
     * @param entityName  entity唯一标识
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_distance.service_id：service的ID
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * set method 
     *
     * @param serviceId  service的ID
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * get method 
     *
     * @return bdmap_distance.coord_type_output：1为 gcj02：国测局加密坐标；2为 bd09ll：百度经纬度坐标
     */
    public String getCoordTypeOutput() {
        return coordTypeOutput;
    }

    /**
     * set method 
     *
     * @param coordTypeOutput  1为 gcj02：国测局加密坐标；2为 bd09ll：百度经纬度坐标
     */
    public void setCoordTypeOutput(String coordTypeOutput) {
        this.coordTypeOutput = coordTypeOutput == null ? null : coordTypeOutput.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_distance.start_time：开始时间
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * set method 
     *
     * @param startTime  开始时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * get method 
     *
     * @return bdmap_distance.end_time：结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * set method 
     *
     * @param endTime  结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * get method 
     *
     * @return bdmap_distance.distance：轨迹里程
     */
    public Float getDistance() {
        return distance;
    }

    /**
     * set method 
     *
     * @param distance  轨迹里程
     */
    public void setDistance(Float distance) {
        this.distance = distance;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entityName=").append(entityName);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", coordTypeOutput=").append(coordTypeOutput);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", distance=").append(distance);
        sb.append("]");
        return sb.toString();
    }
}