package com.wangming.common.auto.model;

import java.io.Serializable;
import java.util.Date;

public class BDMapTrack implements Serializable {
    /**
     * 
     * 表 : bdmap_track
     * 对应字段 : id
     */
    private Integer id;

    /**
     * 起点信息
{
longitude: 114.43693162926,
	latitude: 30.514934681989,
	coord_type: bd09ll,
	loc_time: 1549902620
}
     * 表 : bdmap_track
     * 对应字段 : start_point
     */
    private String startPoint;

    /**
     * 止点信息
{
longitude: 114.43693162926,
	latitude: 30.514934681989,
	coord_type: bd09ll,
	loc_time: 1549902620
}
     * 表 : bdmap_track
     * 对应字段 : end_point
     */
    private String endPoint;

    /**
     * entity唯一标识
     * 表 : bdmap_track
     * 对应字段 : entity_name
     */
    private String entityName;

    /**
     * service的ID
     * 表 : bdmap_track
     * 对应字段 : service_id
     */
    private Integer serviceId;

    /**
     * 1为 gcj02：国测局加密坐标；2为 bd09ll：百度经纬度坐标
     * 表 : bdmap_track
     * 对应字段 : coord_type_output
     */
    private String coordTypeOutput;

    /**
     * 返回了多少条符合条件的轨迹点数量
     * 表 : bdmap_track
     * 对应字段 : size
     */
    private Integer size;

    /**
     * 视频服务开始时间
     * 表 : bdmap_track
     * 对应字段 : service_startdate
     */
    private Date serviceStartdate;

    /**
     * 视频服务截止时间
     * 表 : bdmap_track
     * 对应字段 : service_enddate
     */
    private Date serviceEnddate;

    /**
     * 记录入库时间
     * 表 : bdmap_track
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * 视频客服人员id
     * 表 : bdmap_track
     * 对应字段 : user_id
     */
    private Integer userId;

    /**
     * 求助者（盲人）id
     * 表 : bdmap_track
     * 对应字段 : asker_id
     */
    private String askerId;

    /**
     * 坐标点集合  样例：[106.481766,
29.512927],[106.480841,
29.512731] 
     * 表 : bdmap_track
     * 对应字段 : points
     */
    private String points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bdmap_track
     *
     * @MBG Generated Wed Feb 20 23:41:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return bdmap_track.id：
     */
    public Integer getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get method 
     *
     * @return bdmap_track.start_point：起点信息
{
longitude: 114.43693162926,
	latitude: 30.514934681989,
	coord_type: bd09ll,
	loc_time: 1549902620
}
     */
    public String getStartPoint() {
        return startPoint;
    }

    /**
     * set method 
     *
     * @param startPoint  起点信息
{
longitude: 114.43693162926,
	latitude: 30.514934681989,
	coord_type: bd09ll,
	loc_time: 1549902620
}
     */
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint == null ? null : startPoint.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_track.end_point：止点信息
{
longitude: 114.43693162926,
	latitude: 30.514934681989,
	coord_type: bd09ll,
	loc_time: 1549902620
}
     */
    public String getEndPoint() {
        return endPoint;
    }

    /**
     * set method 
     *
     * @param endPoint  止点信息
{
longitude: 114.43693162926,
	latitude: 30.514934681989,
	coord_type: bd09ll,
	loc_time: 1549902620
}
     */
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint == null ? null : endPoint.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_track.entity_name：entity唯一标识
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * set method 
     *
     * @param entityName  entity唯一标识
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_track.service_id：service的ID
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * set method 
     *
     * @param serviceId  service的ID
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * get method 
     *
     * @return bdmap_track.coord_type_output：1为 gcj02：国测局加密坐标；2为 bd09ll：百度经纬度坐标
     */
    public String getCoordTypeOutput() {
        return coordTypeOutput;
    }

    /**
     * set method 
     *
     * @param coordTypeOutput  1为 gcj02：国测局加密坐标；2为 bd09ll：百度经纬度坐标
     */
    public void setCoordTypeOutput(String coordTypeOutput) {
        this.coordTypeOutput = coordTypeOutput == null ? null : coordTypeOutput.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_track.size：返回了多少条符合条件的轨迹点数量
     */
    public Integer getSize() {
        return size;
    }

    /**
     * set method 
     *
     * @param size  返回了多少条符合条件的轨迹点数量
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * get method 
     *
     * @return bdmap_track.service_startdate：视频服务开始时间
     */
    public Date getServiceStartdate() {
        return serviceStartdate;
    }

    /**
     * set method 
     *
     * @param serviceStartdate  视频服务开始时间
     */
    public void setServiceStartdate(Date serviceStartdate) {
        this.serviceStartdate = serviceStartdate;
    }

    /**
     * get method 
     *
     * @return bdmap_track.service_enddate：视频服务截止时间
     */
    public Date getServiceEnddate() {
        return serviceEnddate;
    }

    /**
     * set method 
     *
     * @param serviceEnddate  视频服务截止时间
     */
    public void setServiceEnddate(Date serviceEnddate) {
        this.serviceEnddate = serviceEnddate;
    }

    /**
     * get method 
     *
     * @return bdmap_track.update_date：记录入库时间
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  记录入库时间
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * get method 
     *
     * @return bdmap_track.user_id：视频客服人员id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * set method 
     *
     * @param userId  视频客服人员id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * get method 
     *
     * @return bdmap_track.asker_id：求助者（盲人）id
     */
    public String getAskerId() {
        return askerId;
    }

    /**
     * set method 
     *
     * @param askerId  求助者（盲人）id
     */
    public void setAskerId(String askerId) {
        this.askerId = askerId == null ? null : askerId.trim();
    }

    /**
     * get method 
     *
     * @return bdmap_track.points：坐标点集合  样例：[106.481766,
29.512927],[106.480841,
29.512731] 
     */
    public String getPoints() {
        return points;
    }

    /**
     * set method 
     *
     * @param points  坐标点集合  样例：[106.481766,
29.512927],[106.480841,
29.512731] 
     */
    public void setPoints(String points) {
        this.points = points == null ? null : points.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", startPoint=").append(startPoint);
        sb.append(", endPoint=").append(endPoint);
        sb.append(", entityName=").append(entityName);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", coordTypeOutput=").append(coordTypeOutput);
        sb.append(", size=").append(size);
        sb.append(", serviceStartdate=").append(serviceStartdate);
        sb.append(", serviceEnddate=").append(serviceEnddate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", userId=").append(userId);
        sb.append(", askerId=").append(askerId);
        sb.append(", points=").append(points);
        sb.append("]");
        return sb.toString();
    }
}