package com.wangming.common.auto.model;

import java.io.Serializable;
import java.util.Date;

public class SpkfAskHelp implements Serializable {
    /**
     * 
     * 表 : spkf_ask_help
     * 对应字段 : id
     */
    private Long id;

    /**
     * 客服人员unionid
     * 表 : spkf_ask_help
     * 对应字段 : unionid
     */
    private String unionid;

    /**
     * 客服我能帮帮忙服务号openid
     * 表 : spkf_ask_help
     * 对应字段 : openid
     */
    private String openid;

    /**
     * 发送消息的appid
     * 表 : spkf_ask_help
     * 对应字段 : appid
     */
    private String appid;

    /**
     * 发送消息设备号
     * 表 : spkf_ask_help
     * 对应字段 : device_id
     */
    private String deviceId;

    /**
     * 视频求助的房间号
     * 表 : spkf_ask_help
     * 对应字段 : room_id
     */
    private String roomId;

    /**
     * 
     * 表 : spkf_ask_help
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spkf_ask_help
     *
     * @MBG Generated Mon Apr 29 10:55:03 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return spkf_ask_help.id：
     */
    public Long getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get method 
     *
     * @return spkf_ask_help.unionid：客服人员unionid
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * set method 
     *
     * @param unionid  客服人员unionid
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * get method 
     *
     * @return spkf_ask_help.openid：客服我能帮帮忙服务号openid
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * set method 
     *
     * @param openid  客服我能帮帮忙服务号openid
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * get method 
     *
     * @return spkf_ask_help.appid：发送消息的appid
     */
    public String getAppid() {
        return appid;
    }

    /**
     * set method 
     *
     * @param appid  发送消息的appid
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * get method 
     *
     * @return spkf_ask_help.device_id：发送消息设备号
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * set method 
     *
     * @param deviceId  发送消息设备号
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * get method 
     *
     * @return spkf_ask_help.room_id：视频求助的房间号
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * set method 
     *
     * @param roomId  视频求助的房间号
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId == null ? null : roomId.trim();
    }

    /**
     * get method 
     *
     * @return spkf_ask_help.create_date：
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", unionid=").append(unionid);
        sb.append(", openid=").append(openid);
        sb.append(", appid=").append(appid);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", roomId=").append(roomId);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }
}