package com.wangming.common.auto.model;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     * 
     * 表 : user_info
     * 对应字段 : id
     */
    private Integer id;

    /**
     * 
     * 表 : user_info
     * 对应字段 : user_name
     */
    private String userName;

    /**
     * 
     * 表 : user_info
     * 对应字段 : password
     */
    private String password;

    /**
     * 
     * 表 : user_info
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 
     * 表 : user_info
     * 对应字段 : appId
     */
    private String appid;

    /**
     * 
     * 表 : user_info
     * 对应字段 : openId
     */
    private String openid;

    /**
     * 
     * 表 : user_info
     * 对应字段 : unionId
     */
    private String unionid;

    /**
     * 
     * 表 : user_info
     * 对应字段 : sex
     */
    private Boolean sex;

    /**
     * 
     * 表 : user_info
     * 对应字段 : city
     */
    private String city;

    /**
     * 
     * 表 : user_info
     * 对应字段 : device_id
     */
    private String deviceId;

    /**
     * 
     * 表 : user_info
     * 对应字段 : headimgurl
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @MBG Generated Sat Feb 23 23:08:54 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return user_info.id：
     */
    public Integer getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get method 
     *
     * @return user_info.user_name：
     */
    public String getUserName() {
        return userName;
    }

    /**
     * set method 
     *
     * @param userName  
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * get method 
     *
     * @return user_info.password：
     */
    public String getPassword() {
        return password;
    }

    /**
     * set method 
     *
     * @param password  
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * get method 
     *
     * @return user_info.create_date：
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return user_info.appId：
     */
    public String getAppid() {
        return appid;
    }

    /**
     * set method 
     *
     * @param appid  
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * get method 
     *
     * @return user_info.openId：
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * set method 
     *
     * @param openid  
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * get method 
     *
     * @return user_info.unionId：
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * set method 
     *
     * @param unionid  
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * get method 
     *
     * @return user_info.sex：
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * set method 
     *
     * @param sex  
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * get method 
     *
     * @return user_info.city：
     */
    public String getCity() {
        return city;
    }

    /**
     * set method 
     *
     * @param city  
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * get method 
     *
     * @return user_info.device_id：
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * set method 
     *
     * @param deviceId  
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * get method 
     *
     * @return user_info.headimgurl：
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * set method 
     *
     * @param headimgurl  
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", createDate=").append(createDate);
        sb.append(", appid=").append(appid);
        sb.append(", openid=").append(openid);
        sb.append(", unionid=").append(unionid);
        sb.append(", sex=").append(sex);
        sb.append(", city=").append(city);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", headimgurl=").append(headimgurl);
        sb.append("]");
        return sb.toString();
    }
}