# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TRTCEducation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TRTCEducation

pod 'TXLiteAVSDK_Professional'

end
